import type { AppData, Cycle } from '../types';
import { makeId, now, withActivity } from './shared';
import { permissions } from '../permissions/permissions';

export const cycleService = {
  create(data:AppData, actorId:string, input:Pick<Cycle,'projectId'|'startDate'|'endDate'|'direction'> & {deliverableIds?:string[]}):AppData { const project=data.projects.find(p=>p.id===input.projectId)!,actor=data.users.find(u=>u.id===actorId); if(!actor||!permissions.canManageProject(actor,project))return data; const number=data.cycles.filter(c=>c.projectId===input.projectId).length+1; const cycle:Cycle={...input,id:makeId('cycle'),deliverableIds:input.deliverableIds||[],number,status:'Active',summary:'',nextPlan:'',createdBy:actorId,createdAt:now()}; let next={...data,cycles:[cycle,...data.cycles],projects:data.projects.map(p=>p.id===input.projectId?{...p,activeCycleId:cycle.id,cycle:{label:`${input.startDate} – ${input.endDate}`,direction:input.direction,deadline:input.endDate}}:p)}; return withActivity(next,input.projectId,actorId,`created Cycle ${String(number).padStart(2,'0')}`); },
  updateDirection(data:AppData, actorId:string, cycleId:string, direction:string):AppData { const cycle=data.cycles.find(c=>c.id===cycleId)!,project=data.projects.find(p=>p.id===cycle.projectId)!,actor=data.users.find(u=>u.id===actorId); if(!actor||!permissions.canGiveDirection(actor,project))return data; const next={...data,cycles:data.cycles.map(c=>c.id===cycleId?{...c,direction}:c),projects:data.projects.map(p=>p.id===cycle.projectId?{...p,cycle:{...p.cycle,direction}}:p)}; return withActivity(next,cycle.projectId,actorId,`updated Principal direction for this cycle`); },
  updatePlan(data:AppData,actorId:string,cycleId:string,input:{startDate:string;endDate:string;direction:string;deliverableIds:string[]}):AppData {const cycle=data.cycles.find(c=>c.id===cycleId)!,project=data.projects.find(p=>p.id===cycle.projectId)!,actor=data.users.find(u=>u.id===actorId);if(!actor||!permissions.canManageProject(actor,project))return data;const next={...data,cycles:data.cycles.map(c=>c.id===cycleId?{...c,...input}:c),projects:data.projects.map(p=>p.id===project.id?{...p,cycle:{label:`${input.startDate} - ${input.endDate}`,direction:input.direction,deadline:input.endDate}}:p)};return withActivity(next,project.id,actorId,'updated the active cycle plan');},
  close(data:AppData, actorId:string, cycleId:string, summary:string, nextPlan:string):AppData { const cycle=data.cycles.find(c=>c.id===cycleId)!,project=data.projects.find(p=>p.id===cycle.projectId)!,actor=data.users.find(u=>u.id===actorId); if(!actor||!permissions.isProjectLead(actor,project))return data; const next={...data,cycles:data.cycles.map(c=>c.id===cycleId?{...c,status:'Closed' as const,summary,nextPlan,closedAt:now()}:c)}; return withActivity(next,cycle.projectId,actorId,`closed the project cycle`); },
  carryForward(data:AppData, actorId:string, itemId:string, targetCycleId:string):AppData { const item=data.workItems.find(w=>w.id===itemId)!,project=data.projects.find(p=>p.id===item.projectId)!,actor=data.users.find(u=>u.id===actorId),target=data.cycles.find(c=>c.id===targetCycleId&&c.projectId===project.id); if(!actor||!permissions.isProjectLead(actor,project)||!target)return data; if(target.deliverableIds?.includes(itemId))return data; const next={...data,cycles:data.cycles.map(c=>c.id===targetCycleId?{...c,deliverableIds:[...(c.deliverableIds||[]),itemId]}:c),workItems:data.workItems.map(w=>w.id===itemId?{...w,carriedFromCycleId:data.cycles.find(c=>c.deliverableIds?.includes(itemId))?.id,updatedAt:now()}:w)}; return withActivity(next,item.projectId,actorId,`carried ${item.name} forward to the next cycle`); },
};
