import type { AppData, DecisionOutcome, Priority } from '../types';
import { makeId, now, withActivity } from './shared';
import { permissions } from '../permissions/permissions';
import { workItemService } from './workItemService';

export const helpRequestService = {
  create(data:AppData, actorId:string, input:{workItemId:string;reason:string;blocked:boolean}):AppData { const item=data.workItems.find(w=>w.id===input.workItemId)!,project=data.projects.find(p=>p.id===item.projectId)!,actor=data.users.find(u=>u.id===actorId); if(!actor||!permissions.canUpdateOwnWork(actor,item))return data; const stamp=now(),isLead=project.leadId===actorId; const request={id:makeId('help'),projectId:item.projectId,workItemId:item.id,raisedBy:actorId,assignedTo:isLead?project.principalId:project.leadId,level:isLead?'principal' as const:'lead' as const,subject:`${input.blocked?'Blocker':'Question'} · ${item.name}`,reason:input.reason,priority:'Normal' as const,status:isLead?'Escalated' as const:'Open' as const,createdAt:stamp,kind:input.blocked?'blocked' as const:'question' as const,...(isLead?{escalatedBy:actorId,escalatedAt:stamp}:{})}; let next={...data,helpRequests:[request,...data.helpRequests]};if(input.blocked)next=workItemService.setStatus(next,actorId,item.id,'Blocked',item.progress,input.reason); return withActivity(next,item.projectId,actorId,`${input.blocked?'reported a blocker':'asked for help'} on ${item.name}`); },
  respond(data:AppData, actorId:string, requestId:string, response:string):AppData { const request=data.helpRequests.find(h=>h.id===requestId)!,project=data.projects.find(p=>p.id===request.projectId)!,actor=data.users.find(u=>u.id===actorId); if(!actor||!permissions.canRespondAsLead(actor,project,request))return data; const next={...data,helpRequests:data.helpRequests.map(h=>h.id===requestId?{...h,response,respondedBy:actorId,respondedAt:now(),status:'Responded' as const}:h)}; return withActivity(next,request.projectId,actorId,`responded to ${request.subject}`); },
  escalate(data:AppData, actorId:string, requestId:string, input:{reason:string;tried:string;decision:string;priority:Priority}):AppData { const request=data.helpRequests.find(h=>h.id===requestId)!,project=data.projects.find(p=>p.id===request.projectId)!,actor=data.users.find(u=>u.id===actorId); if(!actor||!permissions.canEscalateToPrincipal(actor,project,request))return data; const stamp=now(); const next={...data,helpRequests:data.helpRequests.map(h=>h.id===requestId?{...h,level:'principal' as const,assignedTo:project.principalId,reason:input.reason,tried:input.tried,decisionNeeded:input.decision,priority:input.priority,status:'Escalated' as const,escalatedBy:actorId,escalatedAt:stamp}:h)}; return withActivity(next,request.projectId,actorId,`escalated ${request.subject} to ${data.users.find(u=>u.id===project.principalId)?.name}`); },
  markSeen(data:AppData, actorId:string, requestId:string):AppData { const request=data.helpRequests.find(h=>h.id===requestId)!,project=data.projects.find(p=>p.id===request.projectId)!,actor=data.users.find(u=>u.id===actorId); if(!actor||actor.id!==project.principalId)return data; return withActivity({...data,helpRequests:data.helpRequests.map(h=>h.id===requestId&&h.status==='Escalated'?{...h,status:'Seen' as const}:h)},request.projectId,actorId,`acknowledged ${request.subject}`); },
  decide(data:AppData, actorId:string, requestId:string, response:string, outcome:DecisionOutcome):AppData { const request=data.helpRequests.find(h=>h.id===requestId)!,project=data.projects.find(p=>p.id===request.projectId)!,actor=data.users.find(u=>u.id===actorId); if(!actor||!permissions.canDecidePrincipalRequest(actor,project,request))return data; const stamp=now(); const next={...data,helpRequests:data.helpRequests.map(h=>h.id===requestId?{...h,principalDecision:response,decisionOutcome:outcome,decidedBy:actorId,decidedAt:stamp,status:'Decision Given' as const,assignedTo:h.escalatedBy||h.assignedTo}:h)}; return withActivity(next,request.projectId,actorId,`gave a decision on ${request.subject}: ${outcome}`); },
  resolve(data:AppData, actorId:string, requestId:string, note:string):AppData { const request=data.helpRequests.find(h=>h.id===requestId)!,project=data.projects.find(p=>p.id===request.projectId)!,actor=data.users.find(u=>u.id===actorId); if(!actor||!permissions.canResolveRequest(actor,project,request))return data; const stamp=now();const next={...data,helpRequests:data.helpRequests.map(h=>h.id===requestId?{...h,status:'Resolved' as const,resolutionNote:note,resolvedBy:actorId,resolvedAt:stamp}:h),workItems:data.workItems.map(w=>w.id===request.workItemId&&w.status==='Blocked'?{...w,status:'In Progress' as const,blockedReason:undefined,startedAt:stamp,updatedAt:stamp}:w)}; return withActivity(next,request.projectId,actorId,`resolved ${request.subject}`); },
};
