import { useState, type FormEvent } from 'react';
import { createPortal } from 'react-dom';
import { ArrowRight, ChevronDown, Edit3, Plus, Trash2, X } from 'lucide-react';
import type { AppData, Meeting, MeetingGroup, Project, User } from '../types';
import { connectedPeople } from '../domain/people';
import { localDateKey } from '../domain/selectors';
import { permissions } from '../permissions/permissions';
import { meetingService } from '../services/meetingService';
import { Avatar, Empty } from './ui';
import './meetings.css';

type Mutate = (fn: (data: AppData) => AppData) => void;
type MeetingTarget = {kind:'general'}|{kind:'project';project:Project}|{kind:'custom';group:MeetingGroup};
type MeetingType = NonNullable<Meeting['type']>;
const types:MeetingType[]=['Client','Internal','Vendor','Other'];

const displayDate = (date:string) => new Date(`${date}T00:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
const preview = (notes:string) => {const clean=notes.replace(/\s+/g,' ').trim();return clean.length>92?`${clean.slice(0,89)}…`:clean||'No description recorded.'};
const attendeeNames = (data:AppData,meeting:Meeting) => meeting.attendeeIds.map(id=>data.users.find(person=>person.id===id)?.name||'Former team member').join(', ')||'—';
function groupName(data:AppData,meeting:Meeting){if(meeting.projectId)return data.projects.find(project=>project.id===meeting.projectId)?.name||'Project unavailable';if(meeting.groupId)return data.meetingGroups.find(group=>group.id===meeting.groupId)?.name||'General / No Project';return 'General / No Project'}
const targetKey=(target:MeetingTarget)=>target.kind==='general'?'general':`${target.kind}:${target.kind==='project'?target.project.id:target.group.id}`;
const targetName=(target:MeetingTarget)=>target.kind==='general'?'General / No Project':target.kind==='project'?target.project.name:target.group.name;
const targetInput=(target:MeetingTarget)=>target.kind==='project'?{projectId:target.project.id,groupId:undefined}:target.kind==='custom'?{projectId:null,groupId:target.group.id}:{projectId:null,groupId:undefined};

export function MeetingsPage({data,user,mutate}:{data:AppData;user:User;mutate:Mutate}){
  const [expanded,setExpanded]=useState<string[]>([]),[creatingFor,setCreatingFor]=useState<MeetingTarget|null>(null),[selectedId,setSelectedId]=useState<string|null>(null),[deletingMeeting,setDeletingMeeting]=useState<Meeting|null>(null),[creatingGroup,setCreatingGroup]=useState(false),[editingGroup,setEditingGroup]=useState<MeetingGroup|null>(null),[deletingGroup,setDeletingGroup]=useState<MeetingGroup|null>(null);
  const meetings=meetingService.visible(data,user.id),projects=data.projects.filter(project=>!project.archived&&permissions.canViewProject(user,project));
  const groups:MeetingTarget[]=[{kind:'general'},...projects.map(project=>({kind:'project' as const,project})),...data.meetingGroups.map(group=>({kind:'custom' as const,group}))];
  const selected=meetings.find(meeting=>meeting.id===selectedId);
  const inGroup=(meeting:Meeting,target:MeetingTarget)=>target.kind==='project'?meeting.projectId===target.project.id:target.kind==='custom'?meeting.projectId===null&&meeting.groupId===target.group.id:meeting.projectId===null&&!meeting.groupId;
  return <div className="page simple-page meetings-page">
    <div className="simple-title row"><div><p>STUDIO RECORDS</p><h1>Meetings</h1><span>Project discussions and decisions, organised in one register.</span></div><button className="secondary meeting-new-group" onClick={()=>setCreatingGroup(true)}><Plus size={16}/> New category</button></div>
    <div className="meeting-register" aria-label="Meeting register">{groups.map(target=>{const key=targetKey(target),open=expanded.includes(key),entries=meetings.filter(meeting=>inGroup(meeting,target)),project=target.kind==='project'?target.project:null,lead=project&&data.users.find(person=>person.id===project.leadId);return <section className={`meeting-group meeting-group-${target.kind}`} key={key}>
      <div className="meeting-group-head"><button type="button" className="meeting-group-toggle" aria-expanded={open} onClick={()=>setExpanded(current=>current.includes(key)?current.filter(id=>id!==key):[...current,key])}><span><strong>{targetName(target)}</strong>{project&&<small>{project.location||'—'} · Lead: {lead?.name||'—'}</small>}{target.kind==='custom'&&<small>Custom category</small>}</span><span className="meeting-group-count">{entries.length} {entries.length===1?'meeting':'meetings'} <ChevronDown size={17}/></span></button><div className="meeting-group-actions"><button type="button" className="meeting-add" onClick={()=>{setCreatingFor(target);setExpanded(current=>current.includes(key)?current:[...current,key])}}><Plus size={15}/> Add Meeting</button>{target.kind==='custom'&&user.access==='admin'&&<><button type="button" className="meeting-group-icon" aria-label={`Rename ${target.group.name}`} onClick={()=>setEditingGroup(target.group)}><Edit3 size={14}/></button><button type="button" className="meeting-group-icon danger-icon" aria-label={`Delete ${target.group.name}`} onClick={()=>setDeletingGroup(target.group)}><Trash2 size={14}/></button></>}</div></div>
      {open&&<div className="meeting-group-body"><div className="meeting-table-head"><span>DATE</span><span>MEETING</span><span>TYPE</span><span>ATTENDEES</span><span>DESCRIPTION</span><span/></div>{entries.map(meeting=>{const canManage=meeting.createdBy===user.id||user.access==='admin';return <div className={`meeting-register-row ${canManage?'can-manage':''}`} key={meeting.id}><button type="button" className="meeting-row-open" onClick={()=>setSelectedId(meeting.id)}><time dateTime={meeting.date}>{displayDate(meeting.date)}</time><strong>{meeting.title}</strong><span className="meeting-type">{meeting.type||'Other'}</span><span className="meeting-attendee-avatars">{meeting.attendeeIds.slice(0,3).map(id=><Avatar key={id} user={data.users.find(person=>person.id===id)} size="sm"/>)}{meeting.attendeeIds.length>3&&<em>+{meeting.attendeeIds.length-3}</em>}{!meeting.attendeeIds.length&&<small>—</small>}</span><span className="meeting-preview">{preview(meeting.notes)}</span><ArrowRight size={16}/></button>{canManage&&<button type="button" className="meeting-row-delete" aria-label={`Delete ${meeting.title}`} title="Delete meeting" onClick={()=>setDeletingMeeting(meeting)}><Trash2 size={14}/></button>}</div>})}{!entries.length&&<Empty>No meetings recorded in this group.</Empty>}</div>}
    </section>})}</div>
    {creatingFor&&<MeetingForm mode="create" target={creatingFor} data={data} user={user} mutate={mutate} close={()=>setCreatingFor(null)}/>}
    {selected&&<MeetingDetails data={data} user={user} meeting={selected} mutate={mutate} close={()=>setSelectedId(null)}/>}
    {deletingMeeting&&<DeleteMeetingModal meeting={deletingMeeting} user={user} mutate={mutate} close={()=>setDeletingMeeting(null)}/>}
    {creatingGroup&&<GroupNameModal data={data} title="New meeting category" submitLabel="Create category" mutate={mutate} user={user} close={()=>setCreatingGroup(false)}/>}
    {editingGroup&&<GroupNameModal data={data} title="Rename meeting category" submitLabel="Save name" initialName={editingGroup.name} group={editingGroup} mutate={mutate} user={user} close={()=>setEditingGroup(null)}/>}
    {deletingGroup&&<DeleteGroupModal group={deletingGroup} count={meetings.filter(meeting=>meeting.groupId===deletingGroup.id).length} user={user} mutate={mutate} close={()=>setDeletingGroup(null)}/>}
  </div>;
}

function MeetingForm({mode,target,data,user,mutate,close,meeting}:{mode:'create'|'edit';target:MeetingTarget;data:AppData;user:User;mutate:Mutate;close:()=>void;meeting?:Meeting}){
  const initialTarget=meeting?meeting.projectId?`project:${meeting.projectId}`:meeting.groupId?`custom:${meeting.groupId}`:'general':targetKey(target);
  const [date,setDate]=useState(meeting?.date||localDateKey()),[title,setTitle]=useState(meeting?.title||''),[association,setAssociation]=useState(initialTarget),[type,setType]=useState<MeetingType>(meeting?.type||'Other'),[attendeeIds,setAttendeeIds]=useState<string[]>(meeting?.attendeeIds||[]),[notes,setNotes]=useState(meeting?.notes||''),[error,setError]=useState('');
  const projects=data.projects.filter(project=>!project.archived&&permissions.canViewProject(user,project)),people=connectedPeople(data);
  function associationInput(){if(association.startsWith('project:'))return {projectId:association.slice(8),groupId:undefined};if(association.startsWith('custom:'))return {projectId:null,groupId:association.slice(7)};return {projectId:null,groupId:undefined}}
  function submit(event:FormEvent){event.preventDefault();const link=mode==='create'?targetInput(target):associationInput(),input={date,title,...link,type,attendeeIds,notes};const next=mode==='edit'&&meeting?meetingService.update(data,user.id,meeting.id,input):meetingService.create(data,user.id,input);if(next===data){setError('Check the meeting details and try again.');return}mutate(current=>mode==='edit'&&meeting?meetingService.update(current,user.id,meeting.id,input):meetingService.create(current,user.id,input));close()}
  return createPortal(<div className="simple-modal-backdrop" onMouseDown={close}><form className="simple-modal meeting-modal" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><button type="button" className="simple-modal-close" onClick={close} aria-label="Close"><X/></button><p className="modal-kicker">{mode==='create'?'NEW MEETING':'EDIT MEETING'}</p><h2>{mode==='create'?`Record in ${targetName(target)}`:meeting?.title}</h2><label>Date<input type="date" required value={date} onChange={event=>setDate(event.target.value)}/></label><label>Meeting title / subject<input autoFocus required maxLength={160} value={title} onChange={event=>setTitle(event.target.value)} placeholder="What was the meeting about?"/></label>{mode==='edit'&&<label>Project / category<select value={association} onChange={event=>setAssociation(event.target.value)}><option value="general">General / No Project</option>{projects.map(project=><option key={project.id} value={`project:${project.id}`}>{project.name}</option>)}{data.meetingGroups.map(group=><option key={group.id} value={`custom:${group.id}`}>{group.name}</option>)}</select></label>}<label>Type<select value={type} onChange={event=>setType(event.target.value as MeetingType)}>{types.map(value=><option key={value}>{value}</option>)}</select></label><fieldset className="meeting-attendees"><legend>Attendees</legend><div>{people.map(person=><label key={person.id}><input type="checkbox" checked={attendeeIds.includes(person.id)} onChange={()=>setAttendeeIds(current=>current.includes(person.id)?current.filter(id=>id!==person.id):[...current,person.id])}/>{person.name}</label>)}</div>{!people.length&&<small>No Firebase-linked people are available.</small>}</fieldset><label>Notes<textarea value={notes} maxLength={20000} onChange={event=>setNotes(event.target.value)} placeholder="What was discussed or decided?"/></label>{error&&<p className="simple-error" role="alert">{error}</p>}<button className="primary wide" type="submit">{mode==='create'?'Save meeting':'Save changes'}</button></form></div>,document.body);
}

function MeetingDetails({data,user,meeting,mutate,close}:{data:AppData;user:User;meeting:Meeting;mutate:Mutate;close:()=>void}){
  const [editing,setEditing]=useState(false),[deleting,setDeleting]=useState(false),canManage=meeting.createdBy===user.id||user.access==='admin';
  const linkedProject=meeting.projectId?data.projects.find(project=>project.id===meeting.projectId):undefined,linkedGroup=meeting.groupId?data.meetingGroups.find(group=>group.id===meeting.groupId):undefined;
  const target:MeetingTarget=linkedProject?{kind:'project',project:linkedProject}:linkedGroup?{kind:'custom',group:linkedGroup}:{kind:'general'};
  return createPortal(<div className="simple-modal-backdrop" onMouseDown={close}><div className="simple-modal meeting-modal meeting-details" role="dialog" aria-modal="true" aria-label={meeting.title} onMouseDown={event=>event.stopPropagation()}><button type="button" className="simple-modal-close" onClick={close} aria-label="Close"><X/></button><p className="modal-kicker">MEETING RECORD</p><h2>{meeting.title}</h2><dl><div><dt>Date</dt><dd>{displayDate(meeting.date)}</dd></div><div><dt>Project / category</dt><dd>{groupName(data,meeting)}</dd></div><div><dt>Type</dt><dd>{meeting.type||'Other'}</dd></div><div><dt>Attendees</dt><dd>{attendeeNames(data,meeting)}</dd></div></dl><section><h3>Notes</h3><p>{meeting.notes||'No notes recorded.'}</p></section>{canManage&&<div className="meeting-actions"><button className="secondary" onClick={()=>setEditing(true)}><Edit3 size={15}/> Edit</button><button className="meeting-delete-action" onClick={()=>setDeleting(true)}><Trash2 size={15}/> Delete</button></div>}{editing&&<MeetingForm mode="edit" target={target} data={data} user={user} meeting={meeting} mutate={mutate} close={()=>setEditing(false)}/>} {deleting&&createPortal(<div className="simple-modal-backdrop" onMouseDown={()=>setDeleting(false)}><div className="simple-modal meeting-delete-confirm" onMouseDown={event=>event.stopPropagation()}><button className="simple-modal-close" onClick={()=>setDeleting(false)}><X/></button><p className="modal-kicker">DELETE MEETING</p><h2>Delete {meeting.title}?</h2><p>This meeting record and its notes will be permanently deleted.</p><div className="project-delete-actions"><button className="secondary" onClick={()=>setDeleting(false)}>Cancel</button><button className="project-delete-submit" onClick={()=>{mutate(current=>meetingService.delete(current,user.id,meeting.id));close()}}><Trash2 size={15}/> Delete meeting</button></div></div></div>,document.body)}</div></div>,document.body);
}

function GroupNameModal({data,title,submitLabel,initialName='',group,user,mutate,close}:{data:AppData;title:string;submitLabel:string;initialName?:string;group?:MeetingGroup;user:User;mutate:Mutate;close:()=>void}){
  const [name,setName]=useState(initialName),[error,setError]=useState('');
  function submit(event:FormEvent){event.preventDefault();const result=group?meetingService.renameGroup(data,user.id,group.id,name):meetingService.createGroup(data,user.id,name);if(result===data){setError('Use a unique category name.');return}mutate(current=>group?meetingService.renameGroup(current,user.id,group.id,name):meetingService.createGroup(current,user.id,name));close()}
  return createPortal(<div className="simple-modal-backdrop" onMouseDown={close}><form className="simple-modal meeting-category-modal" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><button type="button" className="simple-modal-close" onClick={close}><X/></button><p className="modal-kicker">MEETING CATEGORY</p><h2>{title}</h2><label>Category name<input autoFocus required maxLength={80} value={name} onChange={event=>setName(event.target.value)} placeholder="Office, Consultants, Vendors…"/></label>{error&&<p className="simple-error">{error}</p>}<button className="primary wide" type="submit">{submitLabel}</button></form></div>,document.body);
}

function DeleteGroupModal({group,count,user,mutate,close}:{group:MeetingGroup;count:number;user:User;mutate:Mutate;close:()=>void}){
  return createPortal(<div className="simple-modal-backdrop" onMouseDown={close}><div className="simple-modal meeting-delete-confirm" onMouseDown={event=>event.stopPropagation()}><button className="simple-modal-close" onClick={close}><X/></button><p className="modal-kicker">DELETE CATEGORY</p><h2>Delete {group.name}?</h2><p>The category will be deleted. Its {count} meeting {count===1?'record':'records'} will be kept safely and moved to General / No Project.</p><div className="project-delete-actions"><button className="secondary" onClick={close}>Cancel</button><button className="project-delete-submit" onClick={()=>{mutate(current=>meetingService.deleteGroup(current,user.id,group.id));close()}}><Trash2 size={15}/> Delete category</button></div></div></div>,document.body);
}

function DeleteMeetingModal({meeting,user,mutate,close}:{meeting:Meeting;user:User;mutate:Mutate;close:()=>void}){
  return createPortal(<div className="simple-modal-backdrop" onMouseDown={close}><div className="simple-modal meeting-delete-confirm" onMouseDown={event=>event.stopPropagation()}><button className="simple-modal-close" onClick={close}><X/></button><p className="modal-kicker">DELETE MEETING</p><h2>Delete {meeting.title}?</h2><p>This meeting record and its notes will be permanently deleted.</p><div className="project-delete-actions"><button className="secondary" onClick={close}>Cancel</button><button className="project-delete-submit" onClick={()=>{mutate(current=>meetingService.delete(current,user.id,meeting.id));close()}}><Trash2 size={15}/> Delete meeting</button></div></div></div>,document.body);
}
